global:
  targetRevision: ""

kyverno:
  engine:
    targetRevision: 2.6.0
    replicaCount: 1
  reportsControl:
    enabled: ""
    ui:
      enabled: ""
      useKyvernoPlugin: ""
  reporter:
    targetRevision: 2.17.0
    metrics:
      enabled: true
    rest:
      enabled: true
    api:
      enabled: true
    ui:
      enabled: true
      plugins:
        kyverno: true
    kyvernoPlugin:
      enabled: true