apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environment
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
