{{- if .Values.enable.ingestion.enrichment }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ lower .Values.environment }}-enrichment-psql
  namespace: {{ lower .Values.environment }}-{{ .Values.namespaces.flink }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi

  {{- if .Values.psqlCluster.config.backup.enabled }}
  # Backup config
  backup:
    barmanObjectStore:
      destinationPath: gs://{{ required "gcs bucket is required." .Values.psqlCluster.config.backup.gcpConfig.bucket }}/{{ lower .Values.environment }}
      googleCredentials:
        applicationCredentials:
          name: {{ required "gcs credentials secret is required." .Values.psqlCluster.config.backup.gcpConfig.credentialsSecret.name }}
          key: {{ required "gcs secret key is required." .Values.psqlCluster.config.backup.gcpConfig.credentialsSecret.key }}
    {{- if .Values.psqlCluster.config.backup.retentionPolicy }}
    {{- if mustRegexMatch "^[0-9]{2}$*(d|w|m)$" .Values.psqlCluster.config.backup.retentionPolicy }}
    retentionPolicy: {{ .Values.psqlCluster.config.backup.retentionPolicy }}
    {{- else }}
    {{- fail "retention policy must match the following regular expression: ^[0-9]{2}$*(d|w|m)$. e.g. \"30d\"" }}
    {{- end }}
    {{- end }}
  {{- end }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: weekly-backup-{{ lower .Values.environment }}-enrichment-psql
  namespace: {{ lower .Values.environment }}-{{ .Values.namespaces.flink }}
spec:
  immediate: true
  suspend: false
  schedule: "0 0 0 * * 0" # https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format:~:text=between%20Sat/Sun%20%20%7C-,0%200%200%20*%20*%200,-%40daily%20(or%20%40midnight
  backupOwnerReference: self
  cluster:
    name: {{ lower .Values.environment }}-enrichment-psql
{{- end }}