{{- if .Values.enable.ingestion.enrichment }}
{{- if .Values.psqlCluster.config.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: weekly-backup-{{ lower .Values.environment }}-enrichment-psql
  namespace: {{ lower .Values.environment }}-{{ .Values.namespaces.flink }}
spec:
  immediate: true
  suspend: false
  schedule: "0 0 0 * * 0" # https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format:~:text=between%20Sat/Sun%20%20%7C-,0%200%200%20*%20*%200,-%40daily%20(or%20%40midnight
  backupOwnerReference: cluster
  cluster:
    name: {{ lower .Values.environment }}-enrichment-psql
{{- end }}
{{- end }}