# RBAC configuration for kubernetes-editors Google group
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: kubernetes-editors-group-rbac
rbacBindings:
  - name: cluster-editors
    subjects:
      - kind: Group
        name: kubernetes-editors
{{- $namespaceLen := len .Values.groups.kubernetesEditors.namespaces }}
{{- if or .Values.groups.kubernetesEditors.clusterWide ( eq $namespaceLen 0 ) }}
    clusterRoleBindings:
      - clusterRole: edit
{{- else }}
    roleBindings:
    {{- range $namespace := .Values.groups.kubernetesEditors.namespaces }}
      - clusterRole: edit
        namespace: {{ $namespace }}
    {{- end }}
{{- end }}
      