apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: policy-reporter
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: {{ .Values.kyverno.reporter.targetRevision | quote }}
    helm:
      values: |
        metrics:
          enabled: {{ .Values.kyverno.reporter.metrics.enabled }}
        rest:
          enabled: {{ .Values.kyverno.reporter.rest.enabled }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
