{{- if .Values.kyverno.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: {{ .Values.kyverno.engine.targetRevision }}
    helm:
      values: |
        {{- if .Values.kyverno.engine.highAvailability.enabled }}
        replicaCount: {{ .Values.kyverno.engine.highAvailability.replicas | default 3 }}
        {{- else }}
        replicaCount: {{ .Values.kyverno.engine.replicaCount | default 1 }}
        {{- end }}
        admissionController:
          container:
            resources:
              limits:
                memory: {{ .Values.kyverno.engine.memoryLimit | default "384Mi" }}
              requests:
                memory: {{ .Values.kyverno.engine.memoryLimit | default "384Mi" }} 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
{{- end }}