{{- if .Values.kyverno.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing
    targetRevision: {{ .Values.global.targetRevision | quote }}
    path: components/kyverno-policies
    helm:
      values: |
        failurePolicy: {{ .Values.kyverno.failurePolicy | default "Fail" }}
        policies: {{ toYaml .Values.kyverno.policies | nindent 10 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}