apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-env
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: environment/helm
    repoURL: 'https://github.com/lorenzodagostinoradicalbit/ArgoCD_Kyverno.git'
    targetRevision: develop
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true