apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-new-argo"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - "test-new-argo"