apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/argo-cd
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing.git
    targetRevision: argo-version-switch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
