apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-stack
  namespace: argocd
spec:
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
    - /rules
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_Kyverno
    targetRevision: {{ .Values.global.targetRevision | quote }}
    path: app-stacks/kyverno
    helm:
      values: |
        global:
          targetRevision: {{ .Values.global.targetRevision | quote }}
        kyverno:
          engine:
            highAvailability:
              enabled: {{ .Values.kyverno.engine.highAvailability.enabled }}
          reportsControl:
            enabled: {{ .Values.kyverno.reportsControl.enabled }}
            ui:
              enabled: {{ .Values.kyverno.reportsControl.ui.enabled }}
              useKyvernoPlugin: {{ .Values.kyverno.reportsControl.ui.useKyvernoPlugin }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true