apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/persistentVolumeClaimRetentionPolicy/whenDeleted
        - /spec/persistentVolumeClaimRetentionPolicy/whenScaled
  project: default
  source:
    path: components/monitoring/helm
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing.git
    targetRevision: argo-version-switch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
    
