apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: environment/strimzi-cluster-operator
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing.git
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
