apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.29.0/strimzi-cluster-operator-0.29.0.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
