apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  ## prometheus resource ist synced ok but stuck progressing
  ## this is because crds that does not implement Status are not
  ##  synced by argo sice v2.5
  ##
  ## this will ignore the Prometheus healthcheck
  ##  source: https://github.com/argoproj/argo-cd/issues/11261
  resource.customizations: |
    monitoring.coreos.com/Prometheus:
      health.lua: |
        if obj.metadata.annotations ~= nil and obj.metadata.annotations["argocd.argoproj.io/skip-health-check"] ~= nil then
          hs = {}
          hs.status = "Healthy"
          hs.message = "Ignoring Prometheus Health Check"
          return hs
        end
        
        hs={ status = "Progressing", message = "Waiting for initialization" }
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do

              if condition.type == "Available" and condition.status ~= "True" then
                if condition.reason == "SomePodsNotReady" then
                  hs.status = "Progressing"
                else
                  hs.status = "Degraded"
                end
                hs.message = condition.message or condition.reason
              end
              if condition.type == "Available" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = "All instances are available"
              end
            end
          end
        end
        return hs
  resource.customizations.useOpenLibs.monitoring.coreos.com_Prometheus: 'true'