apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required "Cluster Role name is required." .Values.groups.kubernetesLogViewers.roleName }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch