global:
  environment: local
  targetRevision: rbac-manager
  storageClass: default
  images:
    pullPolicy: IfNotPresent
    pullSecrets: []

rbacManager:
  groupsControl:
    kubernetesAdmins:
      gcpGroupName: "kubernetes-admins"          # @radicalbit.io is added by component
    kubernetesEditors:
      gcpGroupName: "kubernetes-editors"         # @radicalbit.io is added by component
      clusterWide: true
    kubernetesLogViewers:
      gcpGroupName: "kubernetes-log-viewers"     # @radicalbit.io is added by component
      clusterWide: true
    kubernetesPortForwarders:
      gcpGroupName: "kubernetes-port-forwarders" # @radicalbit.io is added by component
      clusterWide: true