apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lorenzodagostinoradicalbit/ArgoCD_env_testing
    targetRevision: develop
    path: components/argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
