{{- if .Values.enable.ingestion.enrichment }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ lower .Values.environment }}-enrichment-psql
  namespace: {{ lower .Values.environment }}-{{ .Values.namespaces.flink }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  {{- if .Values.cnpg.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.cnpg.backup.gcloudBucket }}
      googleCredentials:
        gkeEnvironment: true
  {{- end }}
{{- end }}