{{- if .Values.enable.ingestion.enrichment }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-pg-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: {{ lower .Values.environment }}-enrichment-psql
{{- end }}